sudo: required
language: bash

services:
    - docker

script:
    - docker build -t cosasdepuma/searchsploit Dockerfiles/searchsploit
    - docker run --rm --tty --name searchsploit cosasdepuma/searchsploit --help
